### PR TITLE
Support label and v0.14

### PR DESCRIPTION
**Pull request by repeatedly**
I have one question.
Does this plugin need config-placeholders mixin?

This PR includes indent fix.

### CODE REVIEW

**Comment by tagomoris** [comment]
There seems no features which requires config-placeholder mixin.

**Comment by repeatedly** [comment]
Okay. I will remove it on this PR.

**Comment by repeatedly** [comment]
done

**Comment by tagomoris** [comment]
Do you have time to add very simple test?

**Comment by repeatedly** [comment]
No time ;(

**Comment by tagomoris** [comment]
I added two commits on this at #5.

**Pull request closed without merging**
